{% set name = "lime" %}
{% set version = "0.2.0.0" %}
{% set sha256 = "98310cfa4bc910f304ec7f1850dd8450d1db50bb8e1baec5e84851ea49904714" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - lime

about:
  home: https://github.com/marcotcr/lime
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Explaining the predictions of any machine learning classifier
  doc_url: https://lime-ml.readthedocs.io/
  dev_url: https://github.com/marcotcr/lime

extra:
  recipe-maintainers:
    - proinsias
